services:
  jupyter-notebook:
    image: docker.io/tstuckey303/scs-analysis-jupyter:1.2
    container_name: analysis_container_jupyter
    ports:
      - "7321:8888"
    volumes:
      - "./_data:/home/jovyan/_data"
      - "./notebooks/Jupyter_Notebooks:/home/jovyan/work/notebooks"
    command: "start-notebook.py"
    environment:
      - JUPYTER_TOKEN=scs
    restart: unless-stopped

  sqlitebrowser:
    image: docker.io/linuxserver/sqlitebrowser:3.12.2
    container_name: analysis_container_sqlite
    ports:
      - "7322:3000"
    volumes:
      - "./.config/sqlitebrowser:/config"
      -  "./_data:/config/data"
    restart: unless-stopped 
